# Theme data
theme: jekyll-theme-dinky
title: Sample Programs in Every Language
description: A Collection of Code Snippets in as Many Programming Languages as Possible
google_analytics: UA-97956707-2
show_downloads: true

# Data
image_path: /assets/images/
title_image: sample-programs-in-every-language-featured-image.JPEG

# Repo metadata
repository: TheRenegadeCoder/sample-programs-website

# File exclusion settings
exclude: ["CNAME", "Gemfile", "templates"]

# Markdown interpreter
markdown: GFM

# Posts permalink
permalink: /:categories/:title/

# Extra plugins
plugins:
  - jekyll-feed # See https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-sitemap # See https://github.com/jekyll/jekyll-sitemap

github:
  zip_url: https://github.com/TheRenegadeCoder/sample-programs/zipball/main
  tar_url: https://github.com/TheRenegadeCoder/sample-programs/tarball/main
  repository_url: https://github.com/TheRenegadeCoder/sample-programs
